"""Single source of truth for chart color across the project.

Every hex lives in theme/palette.json. This module is the Python face of that
file; theme/palette.css is the dashboard's face, generated by write_css() below.
Nothing else should hardcode a color.

ONE PALETTE, TWO ORDERINGS. There is a single set of colors -- club gold into
black -- used two ways:

  rank order    content_colors(): gold -> black, in volume order. Pass this as
                color_discrete_map when a chart colors by content_type, so a
                category keeps the same color in every chart it appears in.

  spread order  register(): sets plotly's default colorway to the SAME colors
                re-ordered for maximum separation (palest, darkest, middle...).
                Charts that are not about content_type pass no color arguments
                at all and inherit this.

Why identity rides on lightness rather than hue: no form of colorblindness can
collapse two steps of a one-hue ramp, and it survives greyscale and print.

Why the order is frozen: the step is assigned by content_type NAME, never
recomputed from live counts. If color followed the current rank, two categories
swapping places between pulls would trade colors and readers would see a change
that is not in the data. Re-rank deliberately, by editing the JSON.
"""

import json
from pathlib import Path

# Resolve relative to this file, not the working directory: notebooks run from
# notebooks/ while scripts run from the repo root, and both must find the JSON.
PALETTE_PATH = Path(__file__).resolve().parent.parent / "theme" / "palette.json"
CSS_PATH = PALETTE_PATH.with_suffix(".css")

with open(PALETTE_PATH) as f:
    _P = json.load(f)


def _entries(section):
    """Rows of a section, minus the _comment key used for documentation."""
    return {k: v for k, v in _P[section].items() if k != "_comment"}


# content_type values in rank order, then the residual greys.
RANKED = list(_entries("ramp"))
CONTENT_ORDER = RANKED + list(_entries("residual"))

CHROME = {k: v for k, v in _P["chrome"].items() if k != "_comment"}


def content_colors(mode="light"):
    """content_type -> hex for one surface, in rank order.

    Pass as color_discrete_map on any chart colored by content_type. Prefer this
    over relying on the colorway, which assigns by order of appearance in the
    data rather than by name -- so a filtered chart would repaint its categories.
    """
    colors = {k: v[mode] for k, v in _entries("ramp").items()}
    colors.update({k: v[mode] for k, v in _entries("residual").items()})
    return colors


def colorway(mode="light"):
    """The same colors, re-ordered so the first few are maximally separated.

    The ramp walks gold -> black in small steps, which is right for showing a
    sequence but wrong as a default: a two-series chart would get steps 1 and 2,
    two neighbouring browns. This spreads the picks instead -- palest, darkest,
    middle -- so the common two- or three-series chart reads clearly with no
    color code in the cell at all.
    """
    ramp = [v[mode] for v in _entries("ramp").values()]
    spread = [ramp[i] for i in (0, 5, 2, 4, 1, 3)]
    return spread + [v[mode] for v in _entries("residual").values()]


def register(mode="light"):
    """Install the palette as plotly's default template; return content_colors.

    Also sets the histogram treatment: a pale gold fill with a full-contrast
    outline. A histogram is one series, so its color encodes nothing and should
    recede -- but a pale fill alone sits near 1.6:1 against the surface, and the
    outline at ~6:1 is what keeps each bin legible.
    """
    import plotly.graph_objects as go
    import plotly.io as pio

    fill, line = ("#DCC8A2", "#785C33") if mode == "light" else ("#4A3A22", "#B08F5C")

    pio.templates["lafc"] = go.layout.Template(
        layout=dict(colorway=colorway(mode), bargap=0.02),
        data=dict(
            histogram=[
                go.Histogram(marker_color=fill, marker_line=dict(color=line, width=1))
            ]
        ),
    )
    pio.templates.default = ("plotly_white" if mode == "light" else "plotly_dark") + "+lafc"
    return content_colors(mode)


def write_css(out_path=CSS_PATH):
    """Generate theme/palette.css from the JSON. Run after editing the JSON.

    Emits three blocks because the viewer's theme has three states, not two:
    bare :root carries the full light set; the media query covers an OS dark
    setting; the [data-theme] block covers an explicit toggle. A token defined
    only inside the media query would never apply in the default "system"
    state, which is the classic unreadable-page bug.
    """
    def block(mode, indent="  "):
        rows = {**_entries("ramp"), **_entries("residual")}
        lines = [f"{indent}--ct-{k.replace('_', '-')}: {v[mode]};" for k, v in rows.items()]
        lines += [f"{indent}--chrome-{k}: {v};" for k, v in CHROME.items()]
        return "\n".join(lines)

    css = (
        "/* Generated from theme/palette.json by src/palette.py - do not edit. */\n\n"
        f":root {{\n{block('light')}\n}}\n\n"
        "@media (prefers-color-scheme: dark) {\n"
        '  :root:not([data-theme="light"]) {\n'
        f"{block('dark', '    ')}\n  }}\n}}\n\n"
        f':root[data-theme="dark"] {{\n{block("dark")}\n}}\n'
    )
    Path(out_path).write_text(css)
    return out_path


if __name__ == "__main__":
    print(f"wrote {write_css()}")
