"""Single source of truth for chart color across the project.

Every hex lives in theme/palette.json. This module is the Python face of that
file; theme/palette.css is the dashboard's face, generated by write_css() below.
Nothing else should hardcode a color.

Two palettes, two different jobs:

  RAMP (subject_colors)  One hue, light to dark, ranked by playlist volume.
                         Use where the ranking is the point. Because identity
                         rides on lightness rather than hue, it cannot be
                         broken by any form of colorblindness.

  CATEGORICAL            Five distinct hues for peer categories with no
                         ranking - match-cycle bins, scatter by subject.

Why the ramp order is frozen: the step is assigned by playlist NAME, never
recomputed from live counts. Features (199) and Community & Culture (150) are
close enough to swap after a good month, and if color followed the current
rank they would trade tones between data pulls - readers would see a change
that is not in the data. Re-rank deliberately, by editing the JSON.
"""

import json
from pathlib import Path

# Resolve relative to this file, not the working directory: notebooks run from
# notebooks/ while scripts run from the repo root, and both must find the JSON.
PALETTE_PATH = Path(__file__).resolve().parent.parent / "theme" / "palette.json"
CSS_PATH = PALETTE_PATH.with_suffix(".css")

with open(PALETTE_PATH) as f:
    _P = json.load(f)


def _entries(section):
    """Rows of a section, minus the _comment key used for documentation."""
    return {k: v for k, v in _P[section].items() if k != "_comment"}


# Ranked playlist names, in rank order. Anything outside this list is "Other".
RANKED = list(_entries("ramp"))
SUBJECT_ORDER = RANKED + list(_entries("residual"))

CHROME = {k: v for k, v in _P["chrome"].items() if k != "_comment"}


def subject_colors(mode="light"):
    """Playlist name -> hex for one surface, in rank order.

    Pass the result straight to plotly as color_discrete_map. Prefer this over
    relying on the template's colorway, which assigns by order of appearance in
    the data rather than by category name - so a filtered chart would repaint.
    """
    colors = {k: v[mode] for k, v in _entries("ramp").items()}
    colors.update({k: v[mode] for k, v in _entries("residual").items()})
    return colors


def categorical(mode="light"):
    """The five peer hues as a list, in their validated slot order."""
    return [v[mode] for v in _entries("categorical").values()]


def add_subject(df):
    """Add a 'subject' column: the five ranked playlists, Other, Unlabelled.

    The fold rule lives here, beside the colors, so the two cannot disagree
    about what "Other" means. Videos with no playlist become Unlabelled rather
    than Other - one is a small playlist, the other is missing data, and
    merging them would overstate label coverage by 815 videos.
    """
    # The isna() half of the mask matters: without it, a null playlist fails
    # the isin() test and where() rewrites it to "Other" before fillna() ever
    # sees it - silently merging 815 unlabelled videos into the tail bucket.
    keep = df["playlist"].isin(RANKED) | df["playlist"].isna()
    df["subject"] = df["playlist"].where(keep, "Other").fillna("Unlabelled")
    return df


def register(mode="light"):
    """Install the palette as the default plotly template; return the colors.

    Sets the histogram treatment too, in gold to match the rest of the palette.
    A histogram is one series, so its color encodes nothing and should recede -
    but a pale fill alone sits near 1.6:1 against the surface, and the outline
    at ~6:1 is what keeps each bin legible.
    """
    import plotly.graph_objects as go
    import plotly.io as pio

    colors = subject_colors(mode)
    fill, line = ("#DCC8A2", "#785C33") if mode == "light" else ("#4A3A22", "#B08F5C")

    pio.templates["lafc"] = go.layout.Template(
        layout=dict(colorway=list(colors.values()), bargap=0.02),
        data=dict(
            histogram=[
                go.Histogram(marker_color=fill, marker_line=dict(color=line, width=1))
            ]
        ),
    )
    pio.templates.default = ("plotly_white" if mode == "light" else "plotly_dark") + "+lafc"
    return colors


def write_css(out_path=CSS_PATH):
    """Generate theme/palette.css from the JSON. Run after editing the JSON.

    Emits three blocks because the viewer's theme has three states, not two:
    bare :root carries the full light set; the media query covers an OS dark
    setting; the [data-theme] block covers an explicit toggle. A token defined
    only inside the media query would never apply in the default "system"
    state, which is the classic unreadable-page bug.
    """
    def block(mode, indent="  "):
        rows = {**_entries("ramp"), **_entries("residual")}
        lines = [
            f"{indent}--subject-{i}: {v[mode]};"
            for i, v in enumerate(rows.values(), 1)
        ]
        lines += [
            f"{indent}--cat-{i}: {v[mode]};"
            for i, v in enumerate(_entries("categorical").values(), 1)
        ]
        lines += [f"{indent}--chrome-{k}: {v};" for k, v in CHROME.items()]
        return "\n".join(lines)

    css = (
        "/* Generated from theme/palette.json by src/palette.py - do not edit. */\n\n"
        f":root {{\n{block('light')}\n}}\n\n"
        "@media (prefers-color-scheme: dark) {\n"
        '  :root:not([data-theme="light"]) {\n'
        f"{block('dark', '    ')}\n  }}\n}}\n\n"
        f':root[data-theme="dark"] {{\n{block("dark")}\n}}\n'
    )
    Path(out_path).write_text(css)
    return out_path


if __name__ == "__main__":
    print(f"wrote {write_css()}")
